#!/bin/bash

directorio_destino="${DIRECTORIO_DESTINO:-/etc/coylet}"

case "$1" in
start)
  $directorio_destino/source/run start
  ;;
stop)
  $directorio_destino/source/run stop
  ;;
restart)
  $directorio_destino/source/run restart
  ;;
update)
  $directorio_destino/source/run update
  ;;
check)
  $directorio_destino/source/run check
  ;;
ok)
  $directorio_destino/source/run ok
  ;;
*)
  echo "Uso: $0 {start|stop|restart|update|check|ok}"
  ;;
esac
